name: Documentation
on:
  push:
    branches:
      - '*' # all branches
      - '!main' # exclude main branch
      - '!master' # exclude main branch

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.8
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.8
        id: gitversion
      - name: Main README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "README.md"
      - name: aci-connector README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/aci-connector/README.md"
      - name: aad-integration README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/aad-integration/README.md"
      - name: attach-acr README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/attach-acr/README.md"
      - name: basic README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/basic/README.md"
      - name: best-practices README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/best-practices/README.md"
      - name: monitoring-log-analytics README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/monitoring-log-analytics/README.md"
      - name: network-policy-calico README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/network-policy-calico/README.md"
      - name: spot-node-pool README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/spot-node-pool/README.md"
      - name: user-assigned-identity README.md
        uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "examples/user-assigned-identity/README.md"
      - name: Changelog
        id: changelog
        uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "${{ steps.gitversion.outputs.majorMinorPatch }}"
      - name: Commit CHANGELOG.ms and README.md
        uses: stefanzweifel/git-auto-commit-action@v4
